-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.admin_users (
  id uuid NOT NULL,
  email character varying NOT NULL UNIQUE,
  display_name character varying NOT NULL,
  role USER-DEFINED NOT NULL DEFAULT 'user'::admin_role,
  partenaire_id uuid,
  active boolean DEFAULT true,
  last_login timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  require_password_change boolean DEFAULT true,
  CONSTRAINT admin_users_pkey PRIMARY KEY (id),
  CONSTRAINT admin_users_partenaire_id_fkey FOREIGN KEY (partenaire_id) REFERENCES public.partners(id)
);
CREATE TABLE public.alerts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  titre character varying NOT NULL,
  description text,
  type USER-DEFINED NOT NULL,
  statut USER-DEFINED NOT NULL DEFAULT 'Nouvelle'::alert_status,
  source character varying,
  assigne_a uuid,
  date_creation timestamp with time zone DEFAULT now(),
  date_resolution timestamp with time zone,
  priorite integer DEFAULT 1,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT alerts_pkey PRIMARY KEY (id),
  CONSTRAINT alerts_assigne_a_fkey FOREIGN KEY (assigne_a) REFERENCES public.admin_users(id)
);
CREATE TABLE public.avis (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid,
  partner_id uuid,
  note integer NOT NULL CHECK (note >= 1 AND note <= 5),
  commentaire text,
  type_retour text CHECK (type_retour = ANY (ARRAY['positif'::text, 'negatif'::text])),
  date_avis timestamp with time zone DEFAULT now(),
  approuve boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT avis_pkey PRIMARY KEY (id),
  CONSTRAINT avis_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT avis_employe_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT avis_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.partners(id)
);
CREATE TABLE public.dashboard_widgets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nom character varying NOT NULL,
  type USER-DEFINED NOT NULL,
  configuration jsonb,
  position_x integer,
  position_y integer,
  largeur integer DEFAULT 1,
  hauteur integer DEFAULT 1,
  actif boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dashboard_widgets_pkey PRIMARY KEY (id)
);
CREATE TABLE public.employees (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  partner_id uuid,
  nom character varying NOT NULL,
  prenom character varying NOT NULL,
  genre USER-DEFINED NOT NULL,
  email character varying UNIQUE,
  telephone character varying,
  adresse text,
  poste character varying NOT NULL,
  role character varying,
  type_contrat USER-DEFINED NOT NULL,
  salaire_net numeric,
  date_embauche date,
  actif boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  user_id uuid,
  photo_url character varying,
  CONSTRAINT employees_pkey PRIMARY KEY (id),
  CONSTRAINT employees_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.partners(id),
  CONSTRAINT employees_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.financial_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  montant numeric NOT NULL,
  type USER-DEFINED NOT NULL,
  description text,
  partenaire_id uuid,
  utilisateur_id uuid,
  service_id uuid,
  statut USER-DEFINED NOT NULL DEFAULT 'En attente'::transaction_status,
  date_transaction timestamp with time zone DEFAULT now(),
  date_validation timestamp with time zone,
  reference character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  transaction_id bigint,
  CONSTRAINT financial_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT financial_transactions_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id),
  CONSTRAINT financial_transactions_partenaire_id_fkey FOREIGN KEY (partenaire_id) REFERENCES public.partners(id),
  CONSTRAINT financial_transactions_utilisateur_id_fkey FOREIGN KEY (utilisateur_id) REFERENCES public.employees(id)
);
CREATE TABLE public.historique_remboursements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  remboursement_id uuid NOT NULL,
  action character varying NOT NULL,
  montant_avant numeric,
  montant_apres numeric,
  statut_avant character varying,
  statut_apres character varying,
  description text NOT NULL,
  utilisateur_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT historique_remboursements_pkey PRIMARY KEY (id),
  CONSTRAINT historique_remboursements_remboursement_id_fkey FOREIGN KEY (remboursement_id) REFERENCES public.remboursements(id),
  CONSTRAINT historique_remboursements_utilisateur_id_fkey FOREIGN KEY (utilisateur_id) REFERENCES public.admin_users(id)
);
CREATE TABLE public.historique_remboursements_integraux (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  remboursement_id uuid NOT NULL,
  action character varying NOT NULL,
  montant_avant numeric,
  montant_apres numeric,
  statut_avant character varying,
  statut_apres character varying,
  description text NOT NULL,
  utilisateur_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT historique_remboursements_integraux_pkey PRIMARY KEY (id),
  CONSTRAINT historique_remboursements_integraux_remboursement_id_fkey FOREIGN KEY (remboursement_id) REFERENCES public.remboursements_integraux(id),
  CONSTRAINT historique_remboursements_integraux_utilisateur_id_fkey FOREIGN KEY (utilisateur_id) REFERENCES public.admin_users(id)
);
CREATE TABLE public.notification_cache (
  cache_key character varying NOT NULL,
  cache_value jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone DEFAULT (now() + '01:00:00'::interval),
  CONSTRAINT notification_cache_pkey PRIMARY KEY (cache_key)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  titre character varying NOT NULL,
  message text,
  type USER-DEFINED NOT NULL DEFAULT 'Information'::notification_type,
  lu boolean DEFAULT false,
  date_creation timestamp with time zone DEFAULT now(),
  date_lecture timestamp with time zone,
  employee_id uuid,
  partner_id uuid,
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT notifications_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.partners(id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.admin_users(id)
);
CREATE TABLE public.otp_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email character varying NOT NULL,
  otp character varying NOT NULL CHECK (otp::text ~ '^[0-9]{6}$'::text),
  expires_at timestamp with time zone NOT NULL,
  used boolean DEFAULT false,
  used_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT otp_sessions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.partners (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_name character varying NOT NULL,
  legal_status character varying NOT NULL,
  rccm character varying NOT NULL,
  nif character varying NOT NULL,
  activity_domain character varying NOT NULL,
  headquarters_address text NOT NULL,
  phone character varying NOT NULL CHECK (length(phone::text) <= 20),
  email character varying NOT NULL CHECK (email::text ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'::text),
  employees_count integer NOT NULL CHECK (employees_count > 0),
  payroll character varying NOT NULL,
  cdi_count integer NOT NULL CHECK (cdi_count >= 0),
  cdd_count integer NOT NULL CHECK (cdd_count >= 0),
  payment_date date NOT NULL,
  rep_full_name character varying NOT NULL,
  rep_position character varying NOT NULL,
  rep_email character varying NOT NULL CHECK (rep_email::text ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'::text),
  rep_phone character varying NOT NULL CHECK (length(rep_phone::text) <= 20),
  hr_full_name character varying NOT NULL,
  hr_email character varying NOT NULL CHECK (hr_email::text ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'::text),
  hr_phone character varying NOT NULL CHECK (length(hr_phone::text) <= 20),
  agreement boolean NOT NULL DEFAULT false,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying::text, 'approved'::character varying::text, 'rejected'::character varying::text, 'in_review'::character varying::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  motivation_letter_url text,
  motivation_letter_text text,
  payment_day integer CHECK (payment_day >= 1 AND payment_day <= 31),
  logo_url character varying,
  CONSTRAINT partners_pkey PRIMARY KEY (id)
);
CREATE TABLE public.partnership_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_name character varying NOT NULL,
  legal_status character varying NOT NULL,
  rccm character varying NOT NULL,
  nif character varying NOT NULL,
  activity_domain character varying NOT NULL,
  headquarters_address text NOT NULL,
  phone character varying NOT NULL CHECK (length(phone::text) <= 20),
  email character varying NOT NULL CHECK (email::text ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'::text),
  employees_count integer NOT NULL CHECK (employees_count > 0),
  payroll character varying NOT NULL,
  cdi_count integer NOT NULL CHECK (cdi_count >= 0),
  cdd_count integer NOT NULL CHECK (cdd_count >= 0),
  payment_date date NOT NULL,
  rep_full_name character varying NOT NULL,
  rep_position character varying NOT NULL,
  rep_email character varying NOT NULL CHECK (rep_email::text ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'::text),
  rep_phone character varying NOT NULL CHECK (length(rep_phone::text) <= 20),
  hr_full_name character varying NOT NULL,
  hr_email character varying NOT NULL CHECK (hr_email::text ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'::text),
  hr_phone character varying NOT NULL CHECK (length(hr_phone::text) <= 20),
  agreement boolean NOT NULL DEFAULT false,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying, 'in_review'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  motivation_letter_url text,
  motivation_letter_text text,
  payment_day integer CHECK (payment_day >= 1 AND payment_day <= 31),
  CONSTRAINT partnership_requests_pkey PRIMARY KEY (id)
);
CREATE TABLE public.password_attempts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  ip_address inet,
  user_agent text,
  attempt_count integer DEFAULT 1,
  last_attempt timestamp with time zone DEFAULT now(),
  locked_until timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT password_attempts_pkey PRIMARY KEY (id),
  CONSTRAINT password_attempts_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.performance_metrics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nom character varying NOT NULL,
  valeur numeric NOT NULL,
  unite character varying,
  categorie character varying,
  date_mesure date NOT NULL,
  periode character varying DEFAULT 'jour'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT performance_metrics_pkey PRIMARY KEY (id)
);
CREATE TABLE public.remboursements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  transaction_id uuid NOT NULL UNIQUE,
  demande_avance_id uuid NOT NULL,
  employe_id uuid NOT NULL,
  partenaire_id uuid NOT NULL,
  montant_transaction numeric NOT NULL CHECK (montant_transaction > 0::numeric),
  frais_service numeric DEFAULT 0,
  montant_total_remboursement numeric NOT NULL,
  methode_remboursement USER-DEFINED NOT NULL,
  date_creation timestamp with time zone DEFAULT now(),
  date_transaction_effectuee timestamp with time zone NOT NULL,
  date_limite_remboursement timestamp with time zone NOT NULL,
  date_remboursement_effectue timestamp with time zone,
  statut USER-DEFINED DEFAULT 'EN_ATTENTE'::remboursement_statut,
  numero_compte character varying,
  numero_reception character varying,
  reference_paiement character varying,
  numero_transaction_remboursement character varying,
  commentaire_partenaire text,
  commentaire_admin text,
  motif_retard text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT remboursements_pkey PRIMARY KEY (id),
  CONSTRAINT remboursements_partenaire_id_fkey FOREIGN KEY (partenaire_id) REFERENCES public.partners(id),
  CONSTRAINT remboursements_demande_avance_id_fkey FOREIGN KEY (demande_avance_id) REFERENCES public.salary_advance_requests(id),
  CONSTRAINT remboursements_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.transactions(id),
  CONSTRAINT remboursements_employe_id_fkey FOREIGN KEY (employe_id) REFERENCES public.employees(id)
);
CREATE TABLE public.remboursements_integraux (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  transaction_id uuid NOT NULL UNIQUE,
  demande_avance_id uuid NOT NULL,
  employe_id uuid NOT NULL,
  entreprise_id uuid NOT NULL,
  montant_transaction numeric NOT NULL,
  frais_service numeric DEFAULT 0,
  montant_total_remboursement numeric NOT NULL,
  date_creation timestamp with time zone DEFAULT now(),
  date_transaction_effectuee timestamp with time zone NOT NULL,
  date_limite_remboursement timestamp with time zone NOT NULL,
  date_remboursement_effectue timestamp with time zone,
  statut character varying DEFAULT 'EN_ATTENTE'::character varying CHECK (statut::text = ANY (ARRAY['EN_ATTENTE'::character varying, 'PAYE'::character varying, 'EN_RETARD'::character varying, 'ANNULE'::character varying]::text[])),
  numero_compte character varying,
  numero_reception character varying,
  reference_paiement character varying,
  numero_transaction_remboursement character varying,
  commentaire_entreprise text,
  commentaire_admin text,
  motif_retard text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT remboursements_integraux_pkey PRIMARY KEY (id),
  CONSTRAINT remboursements_integraux_demande_avance_id_fkey FOREIGN KEY (demande_avance_id) REFERENCES public.salary_advance_requests(id),
  CONSTRAINT remboursements_integraux_employe_id_fkey FOREIGN KEY (employe_id) REFERENCES public.employees(id),
  CONSTRAINT remboursements_integraux_entreprise_id_fkey FOREIGN KEY (entreprise_id) REFERENCES public.partners(id),
  CONSTRAINT remboursements_integraux_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.transactions(id)
);
CREATE TABLE public.salary_advance_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employe_id uuid,
  partenaire_id uuid,
  montant_demande numeric NOT NULL,
  type_motif character varying NOT NULL,
  motif text NOT NULL,
  numero_reception character varying,
  frais_service numeric DEFAULT 0,
  montant_total numeric NOT NULL,
  salaire_disponible numeric,
  avance_disponible numeric,
  statut USER-DEFINED NOT NULL DEFAULT 'En attente'::transaction_status,
  date_creation timestamp with time zone DEFAULT now(),
  date_validation timestamp with time zone,
  date_rejet timestamp with time zone,
  motif_rejet text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT salary_advance_requests_pkey PRIMARY KEY (id),
  CONSTRAINT salary_advance_requests_partenaire_id_fkey FOREIGN KEY (partenaire_id) REFERENCES public.partners(id),
  CONSTRAINT salary_advance_requests_employe_id_fkey FOREIGN KEY (employe_id) REFERENCES public.employees(id)
);
CREATE TABLE public.security_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  event_type text NOT NULL,
  ip_address inet,
  user_agent text,
  location_data jsonb,
  risk_score integer DEFAULT 0,
  details jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT security_events_pkey PRIMARY KEY (id),
  CONSTRAINT security_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.services (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nom character varying NOT NULL,
  description text,
  categorie character varying NOT NULL,
  frais_attribues numeric,
  pourcentage_max numeric,
  duree character varying,
  disponible boolean DEFAULT true,
  image_url character varying,
  date_creation timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT services_pkey PRIMARY KEY (id)
);
CREATE TABLE public.transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  demande_avance_id uuid,
  employe_id uuid,
  entreprise_id uuid,
  montant numeric NOT NULL,
  numero_transaction character varying NOT NULL UNIQUE,
  methode_paiement USER-DEFINED NOT NULL,
  numero_compte character varying,
  numero_reception character varying,
  date_transaction timestamp with time zone DEFAULT now(),
  recu_url character varying,
  date_creation timestamp with time zone DEFAULT now(),
  statut USER-DEFINED DEFAULT 'EFFECTUEE'::transaction_statut,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  description text,
  message_callback text,
  CONSTRAINT transactions_pkey PRIMARY KEY (id),
  CONSTRAINT transactions_entreprise_id_fkey FOREIGN KEY (entreprise_id) REFERENCES public.partners(id),
  CONSTRAINT transactions_demande_avance_id_fkey FOREIGN KEY (demande_avance_id) REFERENCES public.salary_advance_requests(id),
  CONSTRAINT transactions_employe_id_fkey FOREIGN KEY (employe_id) REFERENCES public.employees(id)
);
CREATE TABLE public.transactions_backup_before_fix (
  id uuid,
  demande_avance_id uuid,
  employe_id uuid,
  entreprise_id uuid,
  montant numeric,
  numero_transaction character varying,
  methode_paiement USER-DEFINED,
  numero_compte character varying,
  numero_reception character varying,
  date_transaction timestamp with time zone,
  recu_url character varying,
  date_creation timestamp with time zone,
  statut USER-DEFINED,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  description text,
  message_callback text
);
CREATE TABLE public.user_activities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  action character varying NOT NULL,
  details jsonb,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  risk_score integer DEFAULT 0,
  CONSTRAINT user_activities_pkey PRIMARY KEY (id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email character varying NOT NULL UNIQUE,
  nom character varying NOT NULL,
  prenom character varying NOT NULL,
  telephone character varying,
  adresse text,
  type USER-DEFINED NOT NULL DEFAULT 'Étudiant'::user_type,
  statut USER-DEFINED NOT NULL DEFAULT 'En attente'::user_status,
  photo_url character varying,
  organisation character varying,
  poste character varying,
  niveau_etudes character varying,
  etablissement character varying,
  date_inscription timestamp with time zone DEFAULT now(),
  derniere_connexion timestamp with time zone,
  actif boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  encrypted_password text,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);